#注册到eureka上的服务名称
spring:
  application:
    name: service-auth
#redis地址
  redis:
    host: 127.0.0.1
    database: 1
#该服务的端口
server:
  port: 8111
#注册到eureka的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging.level.org.springframework.security: DEBUG

